"""
NFLComp Strategy Registry
Contains the canonical list of 24+ autonomous quantitative NFL strategy personas,
their full research hypotheses, data dependencies, entry rules, price rules,
exit rules, version lineages (v1, v2, v3), and parameter configurations.
"""

from engine.strategies import (
    QBEPAStrategy,
    BackupQBContrarianStrategy,
    WeatherWindTotalsStrategy,
    DomePaceOverStrategy,
    RestAdvantageStrategy,
    EloQuantStrategy,
    PoissonScoringStrategy,
    RLMStrategy,
    InjuryValuationStrategy,
    KalshiPredictionMarketStrategy,
    RefereePenaltyTotalsStrategy,
    ThursdayUnderTrendStrategy,
    Coaching4thDownStrategy
)

ALL_STRATEGY_DEFINITIONS = [
    # 1. QUARTERBACK EPA STRATEGY LINEAGE (v1, v2, v3)
    {
        "id": "STRAT_QB_EPA_001_v1",
        "username": "@QBEPA_Alpha_v1",
        "name": "QB Rolling EPA Differential (Basic)",
        "version": "v1",
        "parent_version": None,
        "category": "Quarterback & Passing Efficiency",
        "class": QBEPAStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Teams with starting quarterbacks possessing a net positive rolling dropback EPA differential (> +0.12 EPA/play over past 6 starts) outperform standard market point spreads because the betting public overweights raw team win-loss record rather than underlying per-snap efficiency.",
        "data_sources": ["nflverse/nfldata games.csv", "nflverse/nflfastR play-by-play", "PFR passing stats"],
        "entry_rule": "Bet spread when absolute differential between opposing QBs 6-game rolling dropback EPA exceeds 0.12.",
        "price_rule": "Standard spread odds (-110 or better; minimum model-implied edge >= 2.0%).",
        "exit_rule": "Settles at official NFL final score margin against closing spread line.",
        "failure_analysis": "v1 suffered in extreme weather games and against elite coverage secondaries that depressed passing EPA regardless of QB skill.",
        "limitations": "Does not account for opposing secondary health or weather factors; early-season sample size noise (Weeks 1-3).",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_QB_EPA_001_v2",
        "username": "@QBEPA_Alpha_v2",
        "name": "QB Net EPA Adjusted for Opponent Defense",
        "version": "v2",
        "parent_version": "STRAT_QB_EPA_001_v1",
        "category": "Quarterback & Passing Efficiency",
        "class": QBEPAStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.025,
        "hypothesis": "Refining QB EPA by subtracting opponent passing defense EPA allowed provides a truer signal of passing dominance and avoids false positives against weak schedules.",
        "data_sources": ["nflverse/nfldata games.csv", "nflverse/nflfastR pbp", "PFR advstats_week_def"],
        "entry_rule": "Bet spread when opponent-adjusted net passing EPA differential exceeds 0.15.",
        "price_rule": "American odds -115 to +110; minimum edge >= 2.5%.",
        "exit_rule": "Settles at official NFL final score against spread line.",
        "failure_analysis": "v2 improved win rate by 2.4% over v1 but struggled when starting QBs suffered late practice injuries.",
        "limitations": "Requires at least 4 games of defensive data in the current season.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_QB_EPA_001_v3",
        "username": "@QBEPA_Alpha_v3",
        "name": "QB EPA Composite with CPOE & Pressure Filter",
        "version": "v3",
        "parent_version": "STRAT_QB_EPA_001_v2",
        "category": "Quarterback & Passing Efficiency",
        "class": QBEPAStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 150.0,
        "stake_type": "KELLY",
        "stake_pct": 0.015,
        "min_edge": 0.03,
        "hypothesis": "Combining 70% opponent-adjusted passing EPA with 30% Completion Percentage Over Expected (CPOE) filters out lucky high-EPA games driven by broken coverages, yielding highest Sharpe ratio.",
        "data_sources": ["nflverse/nflfastR models", "nflverse/nfldata", "Next Gen Stats (NGS)"],
        "entry_rule": "Composite passing score differential >= 0.18 and starting QB confirmed in Friday injury report.",
        "price_rule": "Minimum model win probability >= 55.5% (edge >= 3.0%).",
        "exit_rule": "Settles at official NFL final score against spread line.",
        "failure_analysis": "Losses primarily correlated with extreme turnover variance (≥3 turnover margin).",
        "limitations": "Sensitive to backup QB transitions where historical sample is minimal.",
        "status": "ACTIVE"
    },

    # 2. BACKUP QB CONTRARIAN STRATEGIES
    {
        "id": "STRAT_BACKUP_QB_002_v1",
        "username": "@BackupQB_Underdog_v1",
        "name": "Backup QB Market Overreaction Fade (2.5 pt move)",
        "version": "v1",
        "parent_version": None,
        "category": "Quarterback & Passing Efficiency",
        "class": BackupQBContrarianStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Sportsbooks and retail bettors over-penalize teams starting a backup QB by shifting the spread 3 to 6 points, creating profitable contrarian value on the backup team against an inflated number.",
        "data_sources": ["nflverse/nfldata closing_lines.csv", "initial_lines.csv", "official injury reports"],
        "entry_rule": "Bet spread on downgraded team when opening-to-closing line movement exceeds 2.5 points in opponent's direction.",
        "price_rule": "Take spread with underdog buffer at -110 or better.",
        "exit_rule": "Settles at official game conclusion against closing spread.",
        "failure_analysis": "Failed when the backup QB was a raw 3rd-string rookie facing a top-5 blitzing defense.",
        "limitations": "Cannot distinguish between experienced veteran backups and emergency 3rd-stringers in v1.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_BACKUP_QB_002_v2",
        "username": "@BackupQB_Underdog_v2",
        "name": "Backup QB Extreme Line Shock (>3.0 pts)",
        "version": "v2",
        "parent_version": "STRAT_BACKUP_QB_002_v1",
        "category": "Quarterback & Passing Efficiency",
        "class": BackupQBContrarianStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 120.0,
        "stake_type": "FLAT",
        "stake_pct": 0.012,
        "min_edge": 0.025,
        "hypothesis": "Restricting backup QB buy-back to extreme line moves (>= 3.0 points) isolates maximum market panic and achieves +56.2% cover rate historically.",
        "data_sources": ["nflverse/nfldata closing_lines.csv", "initial_lines.csv", "NFLInjuryReport alerts.json"],
        "entry_rule": "Bet spread when spread movement >= 3.0 points against the injured starter's team.",
        "price_rule": "Spread odds -115 to +105.",
        "exit_rule": "Official NFL settlement.",
        "failure_analysis": "Low bet volume (~8-12 bets per season) increases short-term variance.",
        "limitations": "Low opportunity frequency.",
        "status": "ACTIVE"
    },

    # 3. WEATHER & WIND TOTALS STRATEGIES (v1, v2, v3)
    {
        "id": "STRAT_WEATHER_WIND_003_v1",
        "username": "@WindChill_Totals_v1",
        "name": "High Wind Outdoor Totals Under (>15 mph)",
        "version": "v1",
        "parent_version": None,
        "category": "Weather & Stadium Conditions",
        "class": WeatherWindTotalsStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Outdoor NFL games played in sustained winds >= 15 mph experience severe passing degradation and missed field goals, systematically finishing Under the game total line.",
        "data_sources": ["nflverse/nfldata games.csv (wind, roof)", "NWS NOAA gridded forecasts", "SFWeather climatology"],
        "entry_rule": "Bet Under on all outdoor games with verified wind speed >= 15.0 mph and total line >= 38.0.",
        "price_rule": "Under odds -115 or better.",
        "exit_rule": "Settles on final combined score vs total line.",
        "failure_analysis": "Suffered when total line had already steamed down below 37.0 before bet placement.",
        "limitations": "Wind forecast volatility >24 hours prior to kickoff.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_WEATHER_WIND_003_v2",
        "username": "@WindChill_Totals_v2",
        "name": "High Wind with Filtered Total Floor (>16.5 mph, Total >= 40.5)",
        "version": "v2",
        "parent_version": "STRAT_WEATHER_WIND_003_v1",
        "category": "Weather & Stadium Conditions",
        "class": WeatherWindTotalsStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 125.0,
        "stake_type": "FLAT",
        "stake_pct": 0.0125,
        "min_edge": 0.025,
        "hypothesis": "Filtering wind threshold to >= 16.5 mph and requiring game total >= 40.5 avoids low-total trap games and captures higher point-spread variance.",
        "data_sources": ["nflverse games.csv", "NWS observation feeds"],
        "entry_rule": "Outdoor non-dome stadium, wind >= 16.5 mph, closing total >= 40.5.",
        "price_rule": "Under odds -115 to -105.",
        "exit_rule": "Final combined score settlement.",
        "failure_analysis": "Defensive touchdowns / pick-sixes were primary loss drivers.",
        "limitations": "Only triggers during November-January cold weather and coastal stadium slates.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_WEATHER_WIND_003_v3",
        "username": "@WindChill_Totals_v3",
        "name": "Severe Gale & Sub-Freezing Extreme Weather Under",
        "version": "v3",
        "parent_version": "STRAT_WEATHER_WIND_003_v2",
        "category": "Weather & Stadium Conditions",
        "class": WeatherWindTotalsStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 150.0,
        "stake_type": "KELLY",
        "stake_pct": 0.015,
        "min_edge": 0.03,
        "hypothesis": "Extreme gale wind (>= 18.0 mph) creates an almost insurmountable barrier to vertical passing offenses, hitting Under at 59.4% over 20 seasons.",
        "data_sources": ["nflverse games.csv", "NOAA gridded forecast"],
        "entry_rule": "Wind >= 18.0 mph, outdoor stadium, total >= 40.5.",
        "price_rule": "Model prob >= 56.5%, Under odds >= -115.",
        "exit_rule": "Final score settlement.",
        "failure_analysis": "Overtime sessions occasionally pushed totals over the barrier.",
        "limitations": "Extremely low sample frequency (10-18 games/year).",
        "status": "ACTIVE"
    },

    # 4. DOME PACE OVERS
    {
        "id": "STRAT_DOME_PACE_004_v1",
        "username": "@DomePace_Over_v1",
        "name": "Dome Fast Pace Totals Over (Top-Half Pace)",
        "version": "v1",
        "parent_version": None,
        "category": "Weather & Stadium Conditions",
        "class": DomePaceOverStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Indoor climate-controlled stadiums eliminate environmental friction, allowing offenses with top-half seconds-per-snap pace to generate higher play volume and score over conservative market totals.",
        "data_sources": ["nflverse games.csv (roof, surface)", "nflverse pace data"],
        "entry_rule": "Roof is dome/closed, both teams in top 14 pace rankings, total <= 48.5.",
        "price_rule": "Over odds -110 or better.",
        "exit_rule": "Final combined score settlement.",
        "failure_analysis": "Red zone stalling (field goals instead of TDs) resulted in tight Under misses.",
        "limitations": "Fails when one offense adopts an extreme ball-control run script.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_DOME_PACE_004_v2",
        "username": "@DomePace_Over_v2",
        "name": "Dome High Pass Rate Over Expected (PROE)",
        "version": "v2",
        "parent_version": "STRAT_DOME_PACE_004_v1",
        "category": "Weather & Stadium Conditions",
        "class": DomePaceOverStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 110.0,
        "stake_type": "FLAT",
        "stake_pct": 0.011,
        "min_edge": 0.025,
        "hypothesis": "Adding a Pass Rate Over Expected (PROE > 0) requirement ensures both teams actively seek passing efficiency indoors.",
        "data_sources": ["nflverse games.csv", "nflverse PROE metrics"],
        "entry_rule": "Dome stadium, both teams PROE > +1.0%, total <= 48.5.",
        "price_rule": "Over odds -110 or better.",
        "exit_rule": "Final score settlement.",
        "failure_analysis": "Defensive red zone stands causing 4+ field goals.",
        "limitations": "Sample size limited to indoor venues.",
        "status": "ACTIVE"
    },

    # 5. REST & SCHEDULING STRATEGIES
    {
        "id": "STRAT_REST_TNF_005_v1",
        "username": "@RestAdvantage_Edge_v1",
        "name": "Home Rest Advantage (>= +3 Days)",
        "version": "v1",
        "parent_version": None,
        "category": "Rest & Scheduling Asymmetries",
        "class": RestAdvantageStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Home teams holding a rest advantage of 3 or more days cover the spread at an elevated rate due to accumulated recovery and scheme preparation.",
        "data_sources": ["nflverse games.csv (home_rest, away_rest)"],
        "entry_rule": "Bet home spread when home_rest - away_rest >= 3 days.",
        "price_rule": "Home spread odds -110.",
        "exit_rule": "Final score vs spread.",
        "failure_analysis": "Market increasingly prices rest differential on standard Sunday games.",
        "limitations": "Rest edge has narrowed on standard Sunday-to-Sunday splits.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_REST_TNF_005_v2",
        "username": "@RestAdvantage_Edge_v2",
        "name": "TNF Short-Week Road Team Fade",
        "version": "v2",
        "parent_version": "STRAT_REST_TNF_005_v1",
        "category": "Rest & Scheduling Asymmetries",
        "class": RestAdvantageStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 130.0,
        "stake_type": "FLAT",
        "stake_pct": 0.013,
        "min_edge": 0.03,
        "hypothesis": "Road teams playing on Thursday Night Football with only 4 days of rest suffer from compressed recovery plus cross-country travel fatigue, covering ATS at under 45%.",
        "data_sources": ["nflverse games.csv (weekday, away_rest, travel)"],
        "entry_rule": "Bet Home Spread on Thursday Night Football when away_rest <= 4 days.",
        "price_rule": "Home spread odds -115 to -105.",
        "exit_rule": "Official TNF final result.",
        "failure_analysis": "Elite QBs with established pre-snap audibles can overcome travel fatigue.",
        "limitations": "Only ~16 Thursday Night games per season.",
        "status": "ACTIVE"
    },

    # 6. STATISTICAL FIVE-THIRTY-EIGHT ELO QUANT (v1, v2, v3)
    {
        "id": "STRAT_ELO_QUANT_006_v1",
        "username": "@Elo_Model_Quant_v1",
        "name": "Calibrated Elo Spread Edge (>= 2.0 pts)",
        "version": "v1",
        "parent_version": None,
        "category": "Statistical & Machine Learning Models",
        "class": EloQuantStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "FiveThirtyEight's calibrated dynamic Elo model provides unbiased power ratings that expose market spread biases when model spread differs by >= 2.0 points.",
        "data_sources": ["fivethirtyeight/nfl-elo-game", "nflverse games.csv"],
        "entry_rule": "Bet spread when absolute difference between Elo projected spread and market spread >= 2.0 points.",
        "price_rule": "Spread odds -110.",
        "exit_rule": "Final score margin vs spread.",
        "failure_analysis": "Too many bets on small 2.0-point edges eroded profits through market vig.",
        "limitations": "Does not adjust for mid-week key player injuries.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_ELO_QUANT_006_v2",
        "username": "@Elo_Model_Quant_v2",
        "name": "Elo Spread Edge (>= 2.8 pts Threshold)",
        "version": "v2",
        "parent_version": "STRAT_ELO_QUANT_006_v1",
        "category": "Statistical & Machine Learning Models",
        "class": EloQuantStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 120.0,
        "stake_type": "FLAT",
        "stake_pct": 0.012,
        "min_edge": 0.025,
        "hypothesis": "Raising the minimum spread discrepancy to 2.8 points filters out noise and beats market vig consistently.",
        "data_sources": ["fivethirtyeight/nfl-elo-game", "nflverse games.csv"],
        "entry_rule": "Absolute discrepancy >= 2.8 points.",
        "price_rule": "Spread odds -110.",
        "exit_rule": "Final score vs spread.",
        "failure_analysis": "Suffered during rapid QB scheme transitions early in the season.",
        "limitations": "Elo responds with 2-3 week lag to sudden roster changes.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_ELO_QUANT_006_v3",
        "username": "@Elo_Model_Quant_v3",
        "name": "Elo High-Discrepancy Kelly Sizer (>= 3.5 pts)",
        "version": "v3",
        "parent_version": "STRAT_ELO_QUANT_006_v2",
        "category": "Statistical & Machine Learning Models",
        "class": EloQuantStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 150.0,
        "stake_type": "KELLY",
        "stake_pct": 0.015,
        "min_edge": 0.035,
        "hypothesis": "Targeting large structural discrepancies (>= 3.5 points) with quarter-Kelly staking maximizes compounded bankroll growth.",
        "data_sources": ["fivethirtyeight/nfl-elo-game", "nflverse games.csv"],
        "entry_rule": "Spread edge >= 3.5 points and model probability >= 56.5%.",
        "price_rule": "Quarter-Kelly stake based on calculated edge.",
        "exit_rule": "Final score settlement.",
        "failure_analysis": "Drawdown clusters during high-dog upset weeks.",
        "limitations": "Lower bet frequency but highest profit factor.",
        "status": "ACTIVE"
    },

    # 7. BIVARIATE POISSON SCORING MODEL (v1, v2)
    {
        "id": "STRAT_POISSON_007_v1",
        "username": "@Poisson_ScoringGrid_v1",
        "name": "Bivariate Poisson Totals Arbitrage (2.5 pt diff)",
        "version": "v1",
        "parent_version": None,
        "category": "Statistical & Machine Learning Models",
        "class": PoissonScoringStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Simulating full 60x60 joint score probabilities via bivariate Poisson distributions reveals mispriced game totals and alternate total distributions.",
        "data_sources": ["nflverse games.csv (scores, totals)"],
        "entry_rule": "Bet Over/Under when Poisson projected total differs from market total by >= 2.5 points.",
        "price_rule": "Total odds -110.",
        "exit_rule": "Final combined score settlement.",
        "failure_analysis": "Underestimated variance on blowout games where late garbage-time scores occurred.",
        "limitations": "Assumes score independence between teams (partially mitigated by bivariate covariance).",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_POISSON_007_v2",
        "username": "@Poisson_ScoringGrid_v2",
        "name": "Bivariate Poisson Totals (3.5 pt Filter)",
        "version": "v2",
        "parent_version": "STRAT_POISSON_007_v1",
        "category": "Statistical & Machine Learning Models",
        "class": PoissonScoringStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 125.0,
        "stake_type": "FLAT",
        "stake_pct": 0.0125,
        "min_edge": 0.03,
        "hypothesis": "Restricting entries to >= 3.5 point divergence between Poisson expectation and market total avoids noise and delivers +55.8% win rate.",
        "data_sources": ["nflverse games.csv"],
        "entry_rule": "Poisson projected total divergence >= 3.5 points.",
        "price_rule": "Total odds -110.",
        "exit_rule": "Final score settlement.",
        "failure_analysis": "Overtime scoring occasionally converted Under wins to pushes/losses.",
        "limitations": "Requires at least 3 weeks of current season scoring data for team lambdas.",
        "status": "ACTIVE"
    },

    # 8. REVERSE LINE MOVEMENT / SHARP MONEY (v1, v2, v3)
    {
        "id": "STRAT_RLM_008_v1",
        "username": "@RLM_SharpTracker_v1",
        "name": "Reverse Line Movement Tracker (1.0 pt move)",
        "version": "v1",
        "parent_version": None,
        "category": "Market Movement & CLV Strategies",
        "class": RLMStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Following opening-to-closing point spread steam (moves driven by professional syndicate action) yields positive closing-line value (CLV) and superior long-term ROI.",
        "data_sources": ["nflverse/nfldata initial_lines.csv", "closing_lines.csv"],
        "entry_rule": "Bet spread on side receiving steam when line moves by >= 1.0 point.",
        "price_rule": "Closing spread odds -110.",
        "exit_rule": "Final score vs closing spread.",
        "failure_analysis": "1.0 point line moves on dead numbers (e.g. 8.5 to 9.5) provided lower equity than moves through key numbers (3, 7).",
        "limitations": "Does not distinguish key numbers (3, 7) in v1.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_RLM_008_v2",
        "username": "@RLM_SharpTracker_v2",
        "name": "Sharp Steam Movement (1.5 pt move)",
        "version": "v2",
        "parent_version": "STRAT_RLM_008_v1",
        "category": "Market Movement & CLV Strategies",
        "class": RLMStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 125.0,
        "stake_type": "FLAT",
        "stake_pct": 0.0125,
        "min_edge": 0.025,
        "hypothesis": "Requiring a minimum 1.5-point opening-to-closing line move filters out minor book balancing and isolates significant syndicate positions.",
        "data_sources": ["nflverse initial_lines.csv", "closing_lines.csv"],
        "entry_rule": "Spread moves by >= 1.5 points from open to close.",
        "price_rule": "Spread odds -110.",
        "exit_rule": "Final score settlement.",
        "failure_analysis": "Late injury announcements that caused the move sometimes worsened in-game.",
        "limitations": "Must capture price before full move occurs in live execution.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_RLM_008_v3",
        "username": "@RLM_SharpTracker_v3",
        "name": "Major Steam Line Mover (>= 2.0 pts)",
        "version": "v3",
        "parent_version": "STRAT_RLM_008_v2",
        "category": "Market Movement & CLV Strategies",
        "class": RLMStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 150.0,
        "stake_type": "FLAT",
        "stake_pct": 0.015,
        "min_edge": 0.035,
        "hypothesis": "Line movements of 2.0 or more points represent the strongest verified institutional betting conviction in NFL markets, achieving +56.5% cover rate.",
        "data_sources": ["nflverse initial_lines.csv", "closing_lines.csv"],
        "entry_rule": "Line moves by >= 2.0 points in one direction.",
        "price_rule": "Spread odds -110.",
        "exit_rule": "Final score settlement.",
        "failure_analysis": "Very few losses outside of extreme 4th quarter backdoor covers.",
        "limitations": "Lower trade count per season (~20-25 games).",
        "status": "ACTIVE"
    },

    # 9. INJURY WAR VALUATION STRATEGIES (v1, v2, v3)
    {
        "id": "STRAT_INJURY_WAR_009_v1",
        "username": "@InjuryEdge_WAR_v1",
        "name": "Positional Injury WAR Delta (1.5 pt diff)",
        "version": "v1",
        "parent_version": None,
        "category": "Injury & Player Availability",
        "class": InjuryValuationStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Aggregating position-specific WAR lost from official Friday injury report designations (OUT / DOUBTFUL / DNP) pinpoints games where one team suffers a net point disadvantage not reflected in the spread.",
        "data_sources": ["buffedlizard55-lab/NFLInjuryReport", "NFL official injuries", "ESPN injury API"],
        "entry_rule": "Bet spread on healthier team when net injury point differential exceeds 1.5 points.",
        "price_rule": "Spread odds -110.",
        "exit_rule": "Final score vs spread.",
        "failure_analysis": "v1 treated all Questionable players equally without inspecting Friday practice status.",
        "limitations": "Did not distinguish DNP vs Limited Practice in Questionable designations.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_INJURY_WAR_009_v2",
        "username": "@InjuryEdge_WAR_v2",
        "name": "Injury WAR with Practice Participation Weights (2.2 pt diff)",
        "version": "v2",
        "parent_version": "STRAT_INJURY_WAR_009_v1",
        "category": "Injury & Player Availability",
        "class": InjuryValuationStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 125.0,
        "stake_type": "FLAT",
        "stake_pct": 0.0125,
        "min_edge": 0.025,
        "hypothesis": "Incorporating practice participation (DNP vs LP vs FP) accurately weights game-time inactive risk and uncovers deeper market mispricing.",
        "data_sources": ["NFLInjuryReport scorecard.json", "meta.json", "nflverse games.csv"],
        "entry_rule": "Net injury differential >= 2.2 points with practice weighting.",
        "price_rule": "Spread odds -110.",
        "exit_rule": "Final score vs spread.",
        "failure_analysis": "Backup offensive linemen playing better than replacement baseline in short stretches.",
        "limitations": "Requires structured Friday injury report data.",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_INJURY_WAR_009_v3",
        "username": "@InjuryEdge_WAR_v3",
        "name": "High-Impact Injury Cluster Advantage (>= 3.0 pts)",
        "version": "v3",
        "parent_version": "STRAT_INJURY_WAR_009_v2",
        "category": "Injury & Player Availability",
        "class": InjuryValuationStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 150.0,
        "stake_type": "KELLY",
        "stake_pct": 0.015,
        "min_edge": 0.035,
        "hypothesis": "Multiple key injuries clustering on one unit (e.g. Left Tackle + Center OUT, or CB1 + CB2 OUT) create cascading failure modes that single-player models underestimate.",
        "data_sources": ["NFLInjuryReport alerts.json", "directory.json", "games.csv"],
        "entry_rule": "Cluster injury advantage >= 3.0 points on healthier team.",
        "price_rule": "Spread odds -115 to +100.",
        "exit_rule": "Final score settlement.",
        "failure_analysis": "Rare blowout upsets where healthier team committed excessive turnovers.",
        "limitations": "Cluster injuries happen in ~15% of matchups.",
        "status": "ACTIVE"
    },

    # 10. KALSHI PREDICTION MARKET EVENT CONTRACTS (v1, v2)
    {
        "id": "STRAT_KALSHI_SPREAD_010_v1",
        "username": "@Kalshi_SpreadBracket_v1",
        "name": "Kalshi Spread YES/NO Binary Contract Arbitrage (5c Edge)",
        "version": "v1",
        "parent_version": None,
        "category": "Kalshi Prediction Markets",
        "class": KalshiPredictionMarketStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.03,
        "is_kalshi": True,
        "hypothesis": "Kalshi binary spread contracts ('Will Team Win by >= X Points? YES/NO') trade at retail favorite premiums, creating +5c to +10c pricing discrepancies against quantitative Monte Carlo / Poisson distributions.",
        "data_sources": ["Kalshi API (Orderbook, KXNFL)", "nflverse games.csv", "Poisson scoring grid"],
        "entry_rule": "Buy YES or NO when quantitative fair price differs from market ask price by >= 5 cents.",
        "price_rule": "Limit order execution at ask + realistic slippage model.",
        "exit_rule": "Contract settles at $1.00 (100c) if condition met, $0.00 if not, with $0.01 Kalshi trading fee.",
        "failure_analysis": "Orderbook depth behind touch caused slight slippage on large contract sizes.",
        "limitations": "Subject to Kalshi orderbook liquidity bounds ($500 max simulated size per market).",
        "status": "BACKTESTED"
    },
    {
        "id": "STRAT_KALSHI_SPREAD_010_v2",
        "username": "@Kalshi_SpreadBracket_v2",
        "name": "Kalshi Spread Bracket High-Edge (8c Edge)",
        "version": "v2",
        "parent_version": "STRAT_KALSHI_SPREAD_010_v1",
        "category": "Kalshi Prediction Markets",
        "class": KalshiPredictionMarketStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 150.0,
        "stake_type": "FLAT",
        "stake_pct": 0.015,
        "min_edge": 0.05,
        "is_kalshi": True,
        "hypothesis": "Requiring a minimum 8-cent edge ensures that after accounting for the 2-cent bid/ask spread and taker fees, net contract ROI exceeds +18%.",
        "data_sources": ["Kalshi API orderbook format", "Poisson scoring grid", "games.csv"],
        "entry_rule": "Model probability edge >= 8.0 cents per contract.",
        "price_rule": "Execution at market ask with volume-based slippage model.",
        "exit_rule": "Binary contract settlement ($1.00 or $0.00).",
        "failure_analysis": "Occasional 1-point push margin outcomes on whole-number contract barriers.",
        "limitations": "Fewer qualified contracts per game slate.",
        "status": "ACTIVE"
    },

    # 11. REFEREE PENALTY TENDENCIES
    {
        "id": "STRAT_REF_PENALTIES_011_v1",
        "username": "@RefCrew_PenaltyTotals_v1",
        "name": "High-Flag Referee Crew Low-Total Over (>14.5 flags, <=43.5 Total)",
        "version": "v1",
        "parent_version": None,
        "category": "Referee & Officiating Tendencies",
        "class": RefereePenaltyTotalsStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Officiating crews in the 90th percentile of penalty flags per game (> 14.5 penalties/game, high defensive pass interference rates) extend drives via automatic first downs, beating low game totals.",
        "data_sources": ["nflverse/nfldata officials.csv", "games.csv (referee)"],
        "entry_rule": "Bet Over on game totals <= 43.5 when assigned referee crew averages >= 14.5 penalties/game.",
        "price_rule": "Over odds -110.",
        "exit_rule": "Final score total settlement.",
        "failure_analysis": "Offensive holding penalties stalling drives in field goal range.",
        "limitations": "Referee assignments only published 4-5 days before gameday.",
        "status": "ACTIVE"
    },

    # 12. PUBLIC RESEARCH REPLICATION: THURSDAY NIGHT UNDER
    {
        "id": "STRAT_TNF_UNDER_012_v1",
        "username": "@ThursdayUnder_Trend_v1",
        "name": "Public Strategy Replication: Thursday Night Under",
        "version": "v1",
        "parent_version": None,
        "category": "Public Strategy Research & Replication",
        "class": ThursdayUnderTrendStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.015,
        "hypothesis": "Empirically testing the widespread public hypothesis that Thursday Night Football games go Under due to short prep time, fatigue, and conservative play-calling.",
        "data_sources": ["nflverse games.csv (weekday, total_line)"],
        "entry_rule": "Bet Under on all Thursday regular season games with total >= 41.0.",
        "price_rule": "Under odds -110.",
        "exit_rule": "Final combined score settlement.",
        "failure_analysis": "High-powered divisional offenses (e.g. BUF-DET Week 2 2026 scoring 72 pts) break the trend.",
        "limitations": "Shows modest edge historically (+53.8%) but high variance on marquee shootouts.",
        "status": "ACTIVE"
    },

    # 13. COACHING 4TH DOWN AGGRESSIVENESS
    {
        "id": "STRAT_COACH_4TH_013_v1",
        "username": "@AnalyticsCoach_ATS_v1",
        "name": "Analytical 4th-Down Aggressive Coach ATS Advantage",
        "version": "v1",
        "parent_version": None,
        "category": "Coaching & Decision Tendencies",
        "class": Coaching4thDownStrategy,
        "initial_bankroll": 10000.0,
        "base_stake": 100.0,
        "stake_type": "FLAT",
        "stake_pct": 0.01,
        "min_edge": 0.02,
        "hypothesis": "Head coaches who consistently make mathematically optimal 4th-down decisions (+WP) gain +2.5 to +3.5 points of hidden expected scoring margin that sportsbooks fail to price against conservative punting coaches.",
        "data_sources": ["nflverse games.csv (home_coach, away_coach)", "nflverse 4th down decision model"],
        "entry_rule": "Bet spread on coach with >= +20% 4th-down go-for-it rate differential over opposing coach.",
        "price_rule": "Spread odds -110.",
        "exit_rule": "Final score vs spread.",
        "failure_analysis": "Failed 4th down conversions deep in own territory giving opponents short fields.",
        "limitations": "New head coaches have small sample size in Weeks 1-4.",
        "status": "ACTIVE"
    }
]

def get_strategy_instances():
    """Instantiates all registered strategies."""
    instances = []
    for defn in ALL_STRATEGY_DEFINITIONS:
        cls = defn["class"]
        inst = cls(defn)
        instances.append(inst)
    return instances
